#include $(srctree)/drivers/misc/mediatek/Makefile.custom
ifeq ($(TARGET_PRODUCT), full_tpv6737m_35g_n_s327)
obj-y += hi553mipiraw_Sensor_s327.o
else
obj-y += hi553mipiraw_Sensor.o
endif
#obj-y += Hi553_otp_CZOTP.o
