#
# Copyright (C) 2015 MediaTek Inc.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 2 as
# published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#

#
# Makefile for misc devices that really don't fit anywhere else.
#

ifeq ($(findstring lego,$(ARCH_MTK_PROJECT)), )

ifeq ($(TARGET_PRODUCT), full_tpv6737m_35g_n_s327)
obj-y                           += leds_strobe_s327.o
else
obj-y				+= leds_strobe.o
endif

else
CFILES := leds_strobe.o
obj-m				+= flashlight_device.o
flashlight_device-objs := $(CFILES)
endif
